In [4]:
import pandas as pd
import numpy as np
file_path = "autos_imports-85.csv"
df = pd.read_csv(file_path)
df.head()

        %symboling normalized-losses make fuel-type   aspiration num-of-doors  \
3 ?    alfa-romero               gas  std       two  convertible          rwd
  ?    alfa-romero               gas  std       two  convertible          rwd
1 ?    alfa-romero               gas  std       two    hatchback          rwd
2 164         audi               gas  std      four        sedan          fwd
  164         audi               gas  std      four        sedan          4wd

      body-style  drive-wheels  wheel-base  length  ...  num-of-cylinders  \
3 ?        front          88.6       168.8    64.1  ...               130
  ?        front          88.6       168.8    64.1  ...               130
1 ?        front          94.5       171.2    65.5  ...               152
2 164      front          99.8       176.6    66.2  ...               109
  164      front          99.4       176.6    66.4  ...               136

       engine-size fuel-system  bore  stroke compression-ratio  \
3 ?           mpfi        3.47  2.68     9.0               111
  ?           mpfi        3.47  2.68     9.0               111
1 ?           mpfi        2.68  3.47     9.0               154
2 164         mpfi        3.19  3.40    10.0               102
  164         mpfi        3.19  3.40     8.0               115

      horsepower-peak-rpm city-mpg  highway-mpg  price
3 ?                  5000       21           27  13495
  ?                  5000       21           27  16500
1 ?                  5000       19           26  16500
2 164                5500       24           30  13950
  164                5500       18           22  17450

[5 rows x 24 columns]

In [6]:
df.columns=

NameError: name 'headers' is not defined

In [ ]:
df.describe()

,drive-wheels,wheel-base,length,width,height,num-of-cylinders,stroke,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [ ]:
df.describe(include="all")

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,wheel-base,length,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower-peak-rpm,city-mpg,highway-mpg,price
count,205,205,205,205,205,205,205,205.000000,205.000000,205.000000,...,205.000000,205,205,205,205.000000,205,205,205.000000,205.000000,205
unique,22,2,2,3,5,3,2,NaN,NaN,NaN,...,NaN,8,39,37,NaN,60,24,NaN,NaN,187
top,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,?
freq,32,185,168,114,96,120,202,NaN,NaN,NaN,...,NaN,94,23,20,NaN,19,37,NaN,NaN,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,65.907805,...,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,2.145204,...,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,64.100000,...,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,66.900000,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [ ]:
df.info

In [ ]:
df.drop(subset=["price"], axis = 1, inplace= True)

In [ ]:
mean = df["normalized-losses"].mean()
df["normalized-losses"].replace(np.nan, mean)

TypeError: Could not convert gasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasdieselgasgasdieseldieseldieseldieseldieselgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasdieselgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasdieselgasdieselgasdieselgasdieselgasdieselgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasgasdieseldieselgasgasgasgasgasgasgasgasgasgasgasgasgasgasdieselgasgasgasgasgasgasgasdieselgasdieselgasgasdieselgasgasgasgasdieselgasgasgasgasgasgasgasgasgasgasdieselgas to numeric